version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    
hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.sh
      timeout: 300
  AfterInstall:
    - location: scripts/webserver-start.sh
      timeout: 300
